### ISSUE TITLE
[Bug] Investigate issue with double or more AG registrations

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/effekt-backend#610]
Some donors seem to get multiple AvtaleGiro agreements with the same KID. Could be if they exit the widget and the agreement is drafted, and then go back and do it again somehow?

Investigate what the problem is and create a issue for fixing it with a clear problem description.
```[tasklist]
### Tasks
- [x] Prevent duplicate AG agreements on a schema level
- [ ] Track down cause of duplicate registrations (likely /draft calls?)
- [x] Remove duplicate agreements in database
- [x] Fix cause of duplicate registrations
```
