### ISSUE TITLE
Autogiro

### ISSUE THREAD

**Issue by adamalfredsson** [stiftelsen-effekt/effekt-backend#619]
```[tasklist]
### Tasks
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/669
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/668
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/667
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/666
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/637
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/676
- [x] Setup form for AutoGiro file upload
- [x] Setup form for AutoGiro file download
```
