### ISSUE TITLE
Update DAO functions and routes to support new distribution structure

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/effekt-backend#641]
```[tasklist]
### Tasks
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/642
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/643
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/644
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/645
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/646
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/647
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/648
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/649
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/650
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/651
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/652
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/653
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/654
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/655
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/656
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/657
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/658
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/659
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/660
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/661
- [ ] https://github.com/stiftelsen-effekt/effekt-backend/issues/662
```
