### ISSUE TITLE
Transition fortnox agreements

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/effekt-backend#737]
```[tasklist]
### Tasks
- [ ] Create list of fortnox agreements
- [ ] Sync mandates and agreements with fortnox
- [ ] Remove recurring donations from fortnox agreements
- [ ] Remove filter in scheduled endpoint for agreements
```
